# Generated by Django 4.2.1 on 2023-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_length', models.IntegerField(default=90)),
                ('filename_prefix', models.CharField(max_length=200)),
                ('ringtone_path', models.CharField(max_length=200)),
                ('greeting_message_path', models.CharField(max_length=200)),
                ('beep_tone_path', models.CharField(max_length=200)),
                ('warning_message_path', models.CharField(max_length=200)),
                ('enable_external_speaker_flag', models.BooleanField()),
                ('external_tone_path', models.CharField(max_length=200)),
                ('end_tone_path', models.CharField(max_length=200)),
            ],
        ),
    ]
