# Generated by Django 4.2.1 on 2023-05-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audiobook',
            new_name='Config',
        ),
    ]
