# Generated by Django 4.2.1 on 2023-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_guestbook', '0003_config_speaker_ringtone_play_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
