# Generated by Django 4.2.1 on 2023-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_guestbook', '0004_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='cover',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
