# Generated by Django 4.2.1 on 2023-05-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_guestbook', '0006_remove_photos_name_config_animation_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='external_tone_time',
            field=models.IntegerField(default=120),
        ),
    ]
