# Generated by Django 4.2.1 on 2023-05-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_guestbook', '0007_audio_config_external_tone_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='speaker_ringtone_play_period',
        ),
    ]
