# Generated by Django 4.2.1 on 2023-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_guestbook', '0008_remove_config_speaker_ringtone_play_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='external_tone_time',
        ),
        migrations.AddField(
            model_name='config',
            name='speaker_ringtone_play_period',
            field=models.IntegerField(default=90),
        ),
    ]
